frmset name "bitchx"
frmset author "M-80"
frmset desc "BitchX:Keep it yourself!"
addcolfrm default "0 6 4 9 10 11 12 14 15" "0 15 14"
addpre "%c3ù%c1í%c3ù"
addpre %c8>%c9>%c1>

addform owntext        "%c2<%c9%nick%c2>%c9 %text"
addform chantext       "%c7<%c9%nick%c7>%c9 %text"
addform privtext       "%c7<%c9%nick%c7>%c9 %text"
addform chattext       "%c7<%c9%nick%c7>%c9 %text"
addform hightext       "%c7<%c9%nick%c7>%c9 %text"
addform action         "%c8ð %c1%nick %c9%text"
addform time           "%c9%h%c8:%c9%m%c8%a"
addform addy           "%c9!%c9 %c9@%c9 %c9.%c5"
addform join           "%pre1 %c6%nick %c8\[%c5%user@%thost%c8\] %c9has joined %chan"
addform part           "%pre1 %c9%nick %c8\[%c5%user@%thost%c8\] %c9has left %chan"
addform quit           "%pre1 %c9signoff %c1%nick%c9: %chan %c8(%c9%reason%c8)"
addform kick           "%pre1 %c9%knick was kicked of %chan by %c5%nick %c8(%c9%reason%c8)"
addform nick           "%pre2 %c1%oldnick %c9is now known as %c5%newnick"
addform mode           "%pre1 %c9mode%c8/%c5%chan %c8\[%c1%mode %parms%c8\] %c9by %c1%nick"
addform chanmode       "%pre1 %c9mode%c8/%c5%chan %c8\[%c1%mode%c8\] %c9by %c1%nick"
addform topic          "%pre1 %c1%nick %c9 has changed topic on channel %chan to%c8:%c9%topic"
addform usermode       "%pre1 %c9mode change %c8\[%c1%mode%c8\]"
addform inmsg          "%c8\[13%nick%c8(%c2%user@%host%c8)\] %c9%text"
addform outmsg         "%c8\[%c3msg%c8(5%nick%c8)\] %c9%text"
addform ctcp           "%pre2 %c4%nick %c8\[%c9%user@%host%c8\] %c4requested %ctcp %parms"
addform outctcp        "%c8\[%c3ctcp%c8(5%nick%c8)\] %c9%ctcp %parms"
addform chanctcp       "%c8\[%c3ctcp%c8(5#%nchan%c8)\] %c9%ctcp %parms"
addform ctcprep        "%pre1 %c9CTCP %c1%lctcp %c9reply from %nick:%reply"
addform invite         "%pre2 %c1%nick invites you to join %chan"
addform notice         "%c8-13%nick%c8(%c2%user@%host%c8)- %c9%text"
addform channotice     "%c8-13%nick%c8:%c2%chan%c8- %c9%text"
addform outnotice      "%c8\[%c3notice%c8(5%nick%c8)\] %c9%text"
addform timenow        "%pre1 %c9 the time is %c1%ttime"
addform awaypage       "is away: (%reason) \[BX-MsgLog Off\]"
addform awaynopage     "is away: (%reason) \[BX-MsgLog Off\]"
addform back           "is back: (BX:%reason/%gone)"
addform notify         "%pre1 %c4signon %c9by %c3%nick%c9!%c3user@%host %c9at %ttime"
addform denotify       "%pre1 %c4signoff %c9by %c3%nick%c9!%c3%user@%host %c9at %ttime"
addform onotice        "(%chan/%ops) %text"
addform kill           "%c9%reason:%c1%oper %c9killed %c5%nick %c9at %ttime"
addform sendcreate     "%c8\[5dcc%c8(%c3SEND%c8)\]"
addform sendbegin      "%pre1 %c3DCC %c9SEND connection with %c1%nick%c8\[%c5%nfile%c8\] %c9established"
addform senddone       "%pre1 %c3DCC %c1SEND%c9:%c4%nfile %c8\[%c6%size%c8\] %c9to %nick completed in %time %c8(%c1%cpskps%c8)"
addform senderror      "%pre1 %c3DCC %c1ERROR %c9sending %c4%nfile %c9to %c1%nick"
addform getcreate      "%pre1 %c3DCC %c9GET request from %c5%nick %c8\[%c1%file%c8/%c1%size%c8\]"
addform getbegin       "%pre1 %c3DCC %c9GET connection with %c1%nick%c8\[%c5%nfile%c8\] %c9etablished"
addform getdone        "%pre1 %c3DCC %c1GET%c9:%c4%nfile %c8\[%c6%size%c8\] %c9from %nick completed in %time %c8(%c1%cpskps%c8)"
addform geterror       "%pre1 %c3DCC %c1ERROR %c9getting %c4%nfile %c9from %c1%nick"
addform dnsattempt     "%pre1 %c1doot%c9: checking tables... %c8(%c6%address%c8)"
addform dnsnickattempt "%pre1 %c1doot%c9: Checking tables... %c1%nick%c8(%c6%address%c8)"
addform dnsresolve     "%pre1 %c1doot%c9: %address is %resolve"
addform dnserror       "%pre1 %c1doot%c9: error looking up %address"
addform whoistop       "%c4ÚÄÄÄÄ---3Ä%c4--3ÄÄÄ%c4-3ÄÄÄÄ---%c8ÄÄ3--%c8ÄÄÄ3ÄÄ%c8ÄÄÄÄÄÄ--- --   -"
addform whoisinfo      "%c4³ %c1%nick %c8(%c9%user@%host%c8) %c8(%c1%type%c8)"
addform whoisname      "%c4³ %c1i%c9rcname     %c8:%c9 %name"
addform whoischan      "%c9³ %c1c%c9hannels    %c8:%c9 %chans"
addform whoisserv      "%c8³ %c1s%c9erver      %c8:%c9 %serv (%info)"
addform whoisidle      "%c8³ %c1i%c9dle        %c8:%c9 %idle"
addform whoison        "%c8³ %c1o%c9n          %c8:%c9 %on"
addform whoisircop     "%c8³ %c1i%c9rcop       %c8:%c9 %nick is your %c1gawd %c9 or and ircop"
addform whoisaway      "%c8³ %c1a%c9way        %c8:%c9 %reason"
addform whoisbottom    "                                                                             "
addform whowastop       "%c4ÚÄÄÄÄ---3Ä%c4--3ÄÄÄ%c4-3ÄÄÄÄ---%c8ÄÄ3--%c8ÄÄÄ3ÄÄ%c8ÄÄÄÄÄÄ--- --   -"
addform whowasinfo      "%c4³ %c1%nick %c9 was %c8(%c9%user@%host%c8) %c8(%c1%type%c8)"
addform whowasname      "%c4³ %c1i%c9rcname     %c8:%c9 %name"
addform whowaschan      "%c9³ %c1c%c9hannels    %c8:%c9 %chans"
addform whowasserv      "%c8³ %c1s%c9erver      %c8:%c9 %serv (%info)"
addform whowasbottom    "                                                                             "
addform titlequery      "query\[%nick(%user@%host)time:%time\]"
addform titlechannel    "users:%chan\[+o:%ops/+v:%voice/non:%non\]"
addform titlefinger     "finger\[%nick (+%mode)time:%time\]"
addform titlestatus     "status\[%nick +%mode(%server:%port)time:%time\]"
addform titlechat       "chat\[%nick(%user@%host)time:%time\]"
addform boxtop          "%c6ÚÄÄÄÄ%c5--%c6ÄÄ%c5 %title -%c9Ä%c5--%c9ÄÄÄÄÄ%c5-%c9Ä%c8-  Ä-%c9Ä%c8   --   -   -"
addform boxtop2         "%c6ÚÄÄÄÄ%c5--%c6ÄÄ%c5 %c9%title%c1(%c9%title2%c1) -%c9Ä%c5--%c9ÄÄÄÄÄ%c5-%c9Ä%c8-  Ä-%c9Ä%c8   --   -   -"
addform boxside         "%c6³"
addform boxbottom       "%c6ÀÄÄ%c5Ä--%c9-Ä%c5ÄÄ-Ä%c9ÄÄ%c8Ä%c9-%c8Ä%c9Ä%c8Ä-  - -"
addform bracket         "%c8(%c9%text%c8)"
addform bracket2        "%c8\[%c1%text%c8(%c9%text2%c8)\]"        