# forge format for doot(080798)

frmset name   "forge"
frmset author "mydknight"
frmset desc   "sho nuff."

setcolor cyans
addcolfrm cyans "10 16 15 14 13 6" "14 10 15"

addpre "%c1Ä%c3-%c2-%c3"
addpre "%c4>%c6>%c5>%c3"
addpre "%c4<%c6<%c5<%c3"
addpre "%c5ğ%c6"

addform owntext    "%c6<%c4%nick%c6>%c3 %text"
addform chantext   "%c1(%c3%nick%c1)%c3 %text"
addform privtext   "%c1\[%c3%nick%c1\]%c3 %text"
addform action     "%pre4 %c6%nick %c5%text"
addform hightext   "%c1(%c3%nick%c1)%c3 %text"
addform chattext   "%c1\[%c3%nick%c1\]%c3 %text"

addform time       "%c3%h%c2:%c3%m%a"
addform addy       "%c6!%c3 %c6@%c3 %c6.%c3"

addform join       "%pre1 %c1join%c4\[%c3 %chan %c4\]%c3 %nick!%user@%host"
addform part       "%pre1 %c1leave%c4\[%c3 %chan %c4\]%c3 %nick!%user@%host"
addform quit       "%pre1 %c1signoff%c4\[%c3 %chan %c4\]%c3 %nick!%user@%host %c4(%c3 %reason %c4)%c3"
addform kick       "%pre1 %c1kick%c4\[%c3 %chan %c4\]%c3 %nick %c4(%c3 kicked %knick %c4)%c3 %reason"
addform nick       "%pre1 %c1nick%c4\[%c3 %chan %c4\]%c3 %oldnick %c4(%c3 changed to %newnick %c4)%c3"
addform mode       "%pre1 %c1mode%c4\[%c3 %chan %c4\]%c3 %nick %c4(%c3 %mode %parms %c4)%c3"
addform chanmode   "%pre1 %c1mode%c4\[%c3 %chan %c4\]%c3 %nick %c4(%c3 %mode %c4)%c3"
addform topic      "%pre1 %c1topic%c4\[%c3 %chan %c4\]%c3 %nick %c4(%c3 %topic %c4)%c3"

addform usermode   "%pre1 %c1umode%c4\[%c3 %mode %c4\]%c3"
addform inmsg      "%pre3 %c1msg%c4<%c3%nick!%user@%host%c4\]%c3 %text"
addform outmsg     "%pre2 %c1msg%c4\[%c3%nick%c4>%c3 %text"
addform ctcp       "%pre3 %c1ctcp%c4<%c3%nick!%user@%host%c4\]%c3 %ctcp %parms"
addform outctcp    "%pre2 %c1ctcp%c4\[%c3%nick%c4>%c3 %ctcp %parms"
addform chanctcp   "%pre3 %c1ctcp%c3%chan%c4<%c3%nick!%user@%host%c4\]%c3 %ctcp %parms"
addform ctcprep    "%pre3 %c1reply%c3%ctcp%c4<%c3%nick!%user@%host%c4\]%c3 %reply"
addform invite     "%pre3 %c1invite%c4<%c3%nick!%user@%host%c4\]%c3 %chan"
addform notice     "%c1-%c4<%c3%nick%c4>%c1-%c3 %text"
addform channotice "%c1-%c4<%c3%nick.%chan%c4>%c1-%c3 %text"
addform outnotice  "%pre2 %c1notice%c4\[%c3%nick%c4>%c3 %text"

addform timenow    "%pre1 %c3the time is now %ttime"
addform awaypage   "is gone, %reason (page/on)"
addform awaynopage "is gone, %reason"
addform back       "is back, %reason (gone/%gone)"
addform notify     "%pre1 %c1signon%c4\[%c3 %time %c4\]%c3 %nick!%user@%host"
addform denotify   "%pre1 %c1signoff%c4\[%c3 %time %c4\]%c3 %nick!%user@%host"
addform onotice    "#%chan# %text"
addform kill       "%pre1 %c1kill%c4\[%c3 %time %c4\]%c3 %oper %c4(%c3 killed %nick %c4)%c3 %reason"

addform sendcreate "%pre2 %c1send%c4\[%c3 %nick %c4>%c3 %nfile%c4\[%c3 %size %c4\]%c3"
addform sendbegin  "%pre2 %c1send%c4\[%c3 %nick %c4>%c3 connection established %c4\[%c3 %nfile %c4\]%c3"
addform senddone   "%pre2 %c1send%c4\[%c3 %nick %c4>%c3 send complete %c4\[%c3 %cps %c4\]%c3"
addform senderror  "%pre2 %c1send%c4\[%c3 %nick %c4>%c3 send failed"
addform getcreate  "%pre2 %c1get%c4<%c3 %nick %c4\]%c3 %nfile%c4\[%c3 %size %c4\]%c3"
addform getbegin   "%pre2 %c1get%c4<%c3 %nick %c4\]%c3 connection established %c4\[%c3 %nfile %c4\]%c3"
addform getdone    "%pre2 %c1get%c4<%c3 %nick %c4\]%c3 get complete %c4\[%c3 %cps %c4\]%c3"
addform geterror   "%pre2 %c1get%c4<%c3 %nick %c4\]%c3 get failed"

addform dnsattempt "%pre1 %c1lookup%c4\[%c3 %address %c4>%c3"
addform dnsnickattempt "%pre1 %c1lookup%c4\[%c3 %nick %c4>%c3 %address"
addform dnsresolve "%pre1 %c1lookup%c4\<%c3 %address %c4\]%c3 resolved to %resolve"
addform dnsnoresolve "%pre1 %c1lookup%c4\<%c3 %address %c4\]%c3 unable to resolve"

addform whoistop     "%c4Ú%c1Ä-%c4\[ %c1whois%c3  %c4\]%c3 %nick"
addform whoisinfo    "%c3³%c3ÿ %c4[align "address" 8] %c2:%c3 %user@%host > %type"
addform whoisname    "%c2³%c3ÿ %c4[align "realname" 8] %c3|%c3 %name"
addform whoischan    "%c3³%c3ÿ %c4[align "channels" 8] %c4³%c3 %chans"
addform whoisserv    "%c1³%c3ÿ %c4[align "server" 8] %c1³%c3 %server"
addform whoisidle    "%c1³%c3ÿ %c4[align "idle" 8] %c1³%c3 %idle"
addform whoison      ""
addform whoisircop   "%c1³%c3ÿ %c4[align "oper" 8] %c1³%c3 %nick has fleshy breasts"
addform whoisaway    "%c1³%c3ÿ %c4[align "away" 8] %c1³%c3 %reason"
addform whoisbottom  "%c1À%c4ÄÄ%c3ÄÄ%c2ÄÄÄ%c3ÄÄ%c4ÄÄ%c1Ù"

addform whowastop    "%c4Ú%c1Ä-%c4\[ %c1whowas%c3 %c4\]%c3 %nick"
addform whowasinfo   "%c3³%c3ÿ %c4[align "address" 8] %c2:%c3 %user@%host > %type" 
addform whowasname   "%c2³%c3ÿ %c4[align "realname" 8] %c3|%c3 %name"
addform whowasserv   "%c1³%c3ÿ %c4[align "server" 8] %c1³%c3 %serv"
addform whowasbottom "%c1À%c4ÄÄ%c3ÄÄ%c2ÄÄÄ%c3ÄÄ%c4ÄÄ%c1Ù"

addform titlequery   "query\[ %nick!%user@%host \]"
addform titlechannel "chan\[ %chan \] users\[ %total \] @%time"
addform titlefinger  "finger\[ %user@%host \]"
addform titlestatus  "nick\[ %nick \] modes\[ %mode \] @%time"

addform boxtop       "%c1ÚÄÄÄÄÄ%c4ÄÄÄÄ--%c3-ÄÄÄÄ%c2Ä%c4(%c3 %title %c4)%c2ÄÄÄÄÄ--ÄÄÄÄ%c4ÄÄÄÄÄ-ÄÄÄ%c1Ä-- -%c4--  %c3-%c2-   %c3-     %c4-"
addform boxtop2      "%c1ÚÄÄÄÄÄ%c4ÄÄÄÄ--%c3-ÄÄÄÄ%c2Ä%c4(%c3 %title %c4ğ%c3 %title2 %c4)%c2ÄÄÄÄÄ--ÄÄÄÄ%c4ÄÄÄÄÄ-ÄÄÄ%c1Ä-- -%c4--  %c3-%c2-   %c3-     %c4-"
addform boxside      "%c1³%c3"
addform boxbottom    "%c1ÀÄÄÄ%c4ÄÄ--%c3-ÄÄ%c2ÄÄÄÄ--ÄÄ%c4ÄÄÄ-Ä%c1Ä-- -%c4--  %c3-%c2-   %c3-     %c4- %c1ú%c3 %text"

addform bracket      "%c4(%c2%text%c4)"
addform bracket2     "%c4\[%c2%text%c4(%c3%text2%c4)%c4\]"
