frmset name   "nightstar"
frmset author "pr0jkt"
frmset desc   "this one is for you Barbie:)"
###i made this theme for someone very special in my life, I love you Barbie:)###
addcolfrm default "14 10 11 15 6 13" "14 10 11"
addpre %c3\[%c6û%c3\]
addpre %c6\[%c3û%c6\]
addpre %c1ù%c5ù%c6ù
addform owntext         "%c1(%c6%lnick%c1)%c4 %text"
addform chantext        "%c1(%c4%lnick%c1)%c4 %text"
addform privtext        "%c1(%c4%lnick%c1)%c4 %text"
addform chattext        "%c1(%c4%lnick%c1)%c4 %text"
addform hightext        "%c1(%c3%lnick%c1)%c4 %text"
addform time            "%c1%h%c2:%c1%m%a"
addform addy            "%c1!%c1 %c2@%c1 %c6.%c1"
addform join    "%pre1 %c2\[%c4join%c6(%c2%chan%c6)%c2\] %c4%nick%c2\[%c1%user%c2@%c1%thost%c2\] %c5.%c6.%c2@%c1%ttime"
addform part    "%pre2 %c2\[%c4part%c6(%c4%chan%c6)%c2\] %c4%nick%c2\[%c1%user%c2@%c1%thost%c2\] %c5.%c6.%c2@%c1%ttime"
addform kick    "%pre2 %c2\[%c4kick%c6(%c4%chan%c6)%c2\] %c4%knick%c2\[%c1%reason%c2\] %c4by %nick %c5.%c6.%c2@%c1%ttime"
addform quit    "%pre2 %c2\[%c4quit%c6(%c4%chan%c6)%c2\] %c4%nick%c2\[%c1%reason%c2\] %c5.%c6.%c2@%c1%ttime"
addform nick    "%pre1 %c2\[%c4nick%c6(%c4%oldnick%c6(%c1%user%c2@%c1%thost%c6)%c2\] %c1changed to %c2\[%c4%newnick%c2\] %c5.%c6.%c2@%c1%ttime"
addform mode    "%pre1 %c2\[%c4mode%c6(%c2%chan%c6)%c2\] %c4%nick%c2\[%c4%mode %parms%c2\] %c5.%c6.%c2@%c1%ttime"
addform chanmode  "%pre1 %c2\[%c4mode%c6(%c2%chan%c6)%c2\] %c4%nick%c2\[%c4%mode%c2\] %c5.%c6.%c2@%c1%ttime"
addform usermode        "%pre1 %c1usermode is now %c2\[%c4%mode%c2\] %c5.%c6.%c2@%c1%time"
addform inmsg           "%pre2 %c2\[%c3<%c2-%c4msg%c6(%c4%nick%c6(%c1%user%c2@%c1%thost%c6)%c2\]%c4 %text"
addform outmsg    "%pre1 %c2\[%c4msg%c2-%c3>%c6(%c4%nick%c6)%c2\]%c4 %text"
addform topic     "%pre1 %c2\[%c4topic%c6(%c2%chan%c6)%c2\] %c4%nick%c2\[%c4%topic%c2\] %c5.%c6.%c2@%c1%ttime"
addform timenow         "%pre1 %c1the time is now %c5.%c6.%c2@%c1%ttime"
addform outctcp         "%pre1 %c2\[%c4ctcp%c6(%c1%nick%c6)%c2\]%c4 %lctcp %parms"
addform ctcp            "%pre1 %c2\[%c4ctcp%c6(%c1%lctcp %parms%c6)%c2\] %c4%nick%c2\[%c1%user%c2@%c1%thost%c2\]"
addform chanctcp  "%pre1 %c2\[%c4ctcp%c6(%c2%chan%c6)%c2\] %c4%nick%c2\[%c1%user%c2@%c1%thost%c2\]%c4 %lctcp %parms %c5.%c6.%c2@%c1%ttime"
addform ctcprep   "%pre1 %c2\[%c4%nick%c6(%c1%user%c2@%c1%thost%c6)%c2\] %c4%lctcp %c1reply %c2\[%c4%reply%c2\]"
addform invite    "%pre1 %c2\[%c4invite%c6(%c2%chan%c6)%c2\] %c4%nick%c2\[%c1%user%c2@%c1%thost%c2\] %c5.%c6.%c2@%c1%ttime"
addform action          "%pre3 %c3%nick %c4%text"
addform awaypage        "is away.. %reason (pager)"
addform awaynopage      "is away.. %reason"
addform back            "is back.. %reason (%gone)"
addform notify          "%pre1 %c2\[%c4notify%c6(%c4%nick%c6(%c1%user%c2@%c1%thost%c6)%c2\] %c4is on irc %c5.%c6.%c2@%c1%ttime"
addform denotify        "%pre2 %c2\[%c4denotify%c6(%c4%nick%c6(%c1%user%c2@%c1%thost%c6)%c2\] %c4has left irc %c5.%c6.%c2@%c1%ttime"
addform onotice         "(@%chan/%ops) %text"
addform sendcreate      "%pre1 dcc%c2:%c1 send request sent to %c2\[%c4%nick%c2\]%c1 for %c2\[%c4%nfile%c3/%c4%size%c2\]"
addform getcreate       "%pre1 dcc%c2:%c1 %c2\[%c4%nick%c2\]%c1 is trying to send you %c2\[%c4%nfile%c3/%c4%size%c2\]"
addform sendbegin       "%pre1 dcc%c2:%c1 sending %c2\[%c4%nfile%c3/%c4%size%c2\]%c1 to %c2\[%c4%nick%c2\]"
addform getbegin        "%pre1 dcc%c2:%c1 receiving %c2\[%c4%nfile%c3/%c4%size%c2\]%c1 from %c2\[%c4%nick%c2\]"
addform senddone        "%pre1 dcc%c2:%c1 done sending %c3\[%c2%nfile%c3/%c2%size%c3\]%c1 to %c3\[%c2%nick%c3\]%c1 at %c2\[%c4%cpsk/s%c3 - %c4%time%c2\]"
addform getdone         "%pre1 dcc%c2:%c1 done receiving %c2\[%c4%nfile%c3/%c4%size%c2\]%c1 from %c2\[%c4%nick%c2\]%c1 at %c2\[%c4%cpsk/s%c3 - %c4%time%c2\]"
addform senderror       "%pre1 dcc%c2:%c1 error sending %c2\[%c4%nfile%c2\]%c1 to %c2\[%c4%nick%c2\]"
addform geterror        "%pre1 dcc%c2:%c1 error receiving %c2\[%c4%nfile%c2\]%c1 from %c2\[%c4%nick%c2\]"
addform dnsattempt      "%pre1 dns%c2:%c1 attempting to resolve %c2\[%c4%address%c2\]"
addform dnsnickattempt  "%pre1 dns%c2:%c1 attempting to resolve %c2\[%c4%nick%c5(%c4%address%c5)%c2\]"
addform dnsresolve      "%pre1 dns%c2:%c1 resolved %c2\[%c4%address%c6(%c4%resolve%c6)%c2\]"
addform dnsnoresolve    "%pre1 dns%c2:%c1 unable to resolve %c2\[%c4%address%c2\]"
addform notice          "%pre2 %c2\[%c3<%c2-%c4notice%c6(%c4%nick%c6(%c1%user%c2@%c1%thost%c6)%c2\]%c4 %text"
addform outnotice "%pre1 %c2\[%c4notice%c2-%c3>%c6(%c4%nick%c6)%c2\]%c4 %text"
addform channotice  "%pre2 %c2\[%c3<%c2-%c4notice%c6(%c2%chan%c6(%c4%nick%c5(%c1%user%c2@%c1%thost%c6)%c2\]%c4 %text"
addform kill            "%pre1 %c1kill%c3/%c1%oper%c3(%c2%kills%c3)%c2:%c1 %nick %c2ù%c1 %reason"
addform titlequery      "query(%nick(%user@%host) ..%time"
addform titlechat       "chat(%nick(%user@%host) ..%time"
addform titlechannel    "channel(%chan) users(%total : +o/%op +v/%voice +n/%non) ..%time"
addform titlefinger     "finger(%user@%host) ..%time"
addform titlestatus     "status(%nick - +%mode) on (%server:%port) ..%time"