frmset name "phade"
frmset author "insane"
frmset desc "my pathetic attempt at a theme."

# colors.. i recommend phaded or green.
addcolfrm phaded "11 15 10 12" "15 10 11"
addcolfrm mono "16 15 14 14" "15 14 16"
addcolfrm red "4 14 5 5" "14 5 4"
addcolfrm green "9 15 3 3" "15 3 9"
setcolor phaded

addpre "%c2.%c3.%c1.%c2"
addpre "%c1.%c3.%c2.%c2"

addform owntext "%c2(%c1%lnick%c2) %c2%text"
addform chantext "%c1(%c2%lnick%c1) %c2%text"
addform privtext "%c1(%c2%lnick%c1) %c2%text"
addform hightext "%c1(%c2%lnick%c1) %c2%text"
addform action "%c1í %c2%nick %text"
addform time "%c2%h:%m%c1"
addform addy "%c1!%c2 %c1@%c2 %c2.%c2"
addform join "%pre1 %c2join%c3\[%c2%chan%c3\]%c2 %nick%c1(%c2%user@%host%c1)%c2 ..%time"
addform part "%pre1 %c2part%c3\[%c2%chan%c3\]%c2 %nick%c1(%c2%user@%host%c1)%c2 ..%time"
addform quit "%pre1 %c2quit%c3\[%c2%chan%c3\]%c2 %nick%c1(%c2%user@%host%c1)%c2 - %c3(%c2%reason%c3)%c2..%time"
addform kick "%pre1 %c2kick%c3\[%c2%chan%c3\]%c2 %knick%c2 was kicked by %nick %c1(%c2%reason%c1)%c2..%time"
addform nick "%pre1 %c2nick%c3\[%c2%chan%c3\]%c2 %oldnick %c3--%c1>%c2 %newnick%c2"
addform mode "%pre1 %c2mode%c3\[%c2%chan%c3\]%c2 %nick sets mode %c1(%c2%mode/%parms%c1)%c2 ..%time"
addform chanmode "%pre1 %c2mode%c3\[%c2%chan%c3\]%c2 %nick sets mode %c1(%c2%mode%c1)%c2 ..%time"
addform topic "%pre1 %c2topic%c3\[%c2%chan%c3\]%c2 %nick sets topic %c1(%c2%topic%c1)%c2"
addform usermode "%pre2 %c2usermodes%c3:%c2 now set to %c1%mode%c2"
addform inmsg "%c1\[%c2%nick%c3(%c2%user@%host%c3)%c1\]%c2 %text"
addform outmsg "%c1\[%c2msg%c3(%c2%nick%c3)%c1\]%c2 %text"
addform ctcp "%pre2 %c1\[%c2ctcp%c3(%c2from %nick%c3)%c1\]%c2 %ctcp %parms"
addform outctcp "%pre2 %c1\[%c2ctcp%c3(%c2%nick%c3)%c1\]%c2 %ctcp %parms"
addform chanctcp "%pre1 %c2ctcp%c1\[%c2%chan%c1\]%c2 %nick - %ctcp %parms"
addform ctcprep "%pre2 %c1\[%c2ctcpreply%c3(%c2%nick%c3)%c1\]%c2 %reply"
addform invite "%pre2 %nick%c1(%c2%user@%host%c1)%c2 invites you to join %chan %c1(%c2press f1 to join%c1)%c2"
addform timenow "%pre2 the time is now %time"
addform awaypage "away, %reason (msglog!on)"
addform awaynopage "away, %reason (msglog!on)"
addform back "back, %reason ..(%gone)"
addform notify "%pre2 %c1(%c2notify%c1)%c2 %nick%c3(%c2%user@%host%c3)%c2 is on irc ..%time"
addform denotify "%pre2 %c1(%c2denotify%c1)%c2 %nick%c3(%c2%user@%host%c3)%c2 has left irc ..%time"
addform onotice "\[wall(%chan/%ops)\] %text"
addform kill "%pre2 %c1\[%c2kill%c3(%c2%oper%c3)%c1\]%c2 killed %nick %c1(%c2%reason%c1)%c2 ..total: %kills"
addform sendcreate "%pre2 %c1(%c2dcc send%c3/%c2%nick%c1)%c2 %file%c3/%c2%size"
addform getcreate "%pre2 %c1(%c2dcc get%c3/%c2%nick%c1)%c2 %nfile%c3/%c2%size"
addform sendbegin "%pre2 %c1(%c2dcc send%c3/%c2%nick%c1)%c2 transfer initiated: %file%c3/%c2%size"
addform getbegin "%pre2 %c1(%c2dcc get%c3/%c2%nick%c1)%c2 transfer initiated: %nfile%c3/%c2%size"
addform senddone "%pre2 %c1(%c2dcc send%c3/%c2%nick%c1)%c2 transfer completed%c3(%c2%file%c3)%c2"
addform getdone "%pre2 %c1(%c2dcc get%c3/%c2%nick%c1)%c2 transfer completed%c3(%c2%nfile%c3)%c2"
addform senderror "%pre2 %c1(%c2dcc send%c3/%c2%nick%c1)%c2 error in transfer: %file"
addform geterror "%pre2 %c1(%c2dcc get%c3/%c2%nick%c1)%c2 error in transfer: %nfile"
addform dnsattempt "%pre2 %c1(%c2nslookup%c1)%c2 attempting to resolve %c1%address%c2"
addform dnsnickattempt "%pre2 %c1(%c2nslookup%c1)%c2 attempting to resolve %nick%c3(%c2%address%c3)%c2"
addform dnsresolve "%pre2 %c1(%c2nslookup%c1)%c2 resolved %c1%address%c2 to %c1%resolve%c2"
addform dnsnoresolve "%pre2 %c1(%c2nslookup%c1)%c2 unable to resolve %c1%address%c2"
addform titlequery "%nick(%user@%host)"
addform titlechannel "%chan(o:%op/v:%voice/n:%non/t:%total)"
addform titlefinger "finger(%user @ %host)"
addform titlestatus "%nick(+%mode) on %server:%port"
addform boxtop "%c1Ú%c2Ä%c3ÄÄÄÄ%c2Ä%c1ÄÄÄÄ%c2Ä%c3ÄÄ%c1ÄÄÄÄ %title %c3ÄÄÄÄÄÄ%c2ÄÄÄ%c1ÄÄ%c3- -%c1ÄÄ%c2-"
addform boxtop2 "%c1Ú%c2Ä%c3ÄÄÄÄ%c2Ä%c1ÄÄÄÄ%c2Ä%c3ÄÄ%c1ÄÄÄÄ %title/%title2 %c3ÄÄÄÄÄÄ%c2ÄÄÄ%c1ÄÄ%c3- -%c1ÄÄ%c2-"
addform boxside "%c1³%c2"
addform boxbottom "%c1ÀÄ%c2ÄÄ%c3Ä %c1-%c2ÄÄ%c3Ä"
addform whoistop "%c1ÚÄ%c2ÄÄÄ%c3ÄÄ%c2Ä%c3Ä%c1ÄÄ%c3ÄÄÄ%c2ÄÄÄÄ%c1Ä whois%c1(%c2%nick%c1)%c2 ÄÄÄ%c3Ä%c2ÄÄ%c3ÄÄ%c1ÄÄÄ%c3Ä- %c2ÄÄ%c1- %c3-%c2"
addform whoisinfo "%c2³ %c1i%c2nfo    %c3:%c2 %user%c1@%c2%host %c1(%c2%type%c1)%c2"    
addform whoisname "%c2³ %c1q%c2uote   %c3:%c2 %name"
addform whoischan "%c2³ %c1c%c2hans   %c3:%c2 %chans"
addform whoisserv "%c2³ %c1s%c2erver  %c3:%c2 %serv %c1(%c2%info%c1)%c2"
addform whoisidle "%c2³ %c1i%c2dle    %c3:%c2 %idle"
addform whoisircop "%c2³ %c1o%c2per    %c3:%c2 fear."
addform whoisaway "%c2³ %c1a%c2way    %c3:%c2 %reason"
addform whoisbottom "%c1ÀÄ%c2ÄÄ%c3ÄÄÄ%c1Ä%c3-%c2"
addform whowastop "%c1ÚÄ%c2ÄÄÄ%c3ÄÄ%c2Ä%c3Ä%c1ÄÄ%c3ÄÄÄ%c2ÄÄÄÄ%c1Ä whowas%c1(%c2%nick%c1)%c2 ÄÄÄ%c3Ä%c2ÄÄ%c3ÄÄ%c1ÄÄÄ%c3Ä- %c2ÄÄ%c1- %c3-%c2"
addform whowasinfo "%c2³ %c1i%c2nfo    %c3:%c2 %user%c1@%c2%host %c1(%c2%type%c1)%c2" 
addform whowasname "%c2³ %c1q%c2uote   %c3:%c2 %name"
addform whowasserv "%c2³ %c1s%c2erver  %c3:%c2 %serv"
addform whowasbottom "%c1ÀÄ%c2ÄÄ%c3ÄÄÄ%c1Ä%c3-%c2"
#addform notice "%c3-%c2%nick%c3(%c2%user@%host%c3)-%c2 %text"
addform outnotice "%c1\[%c2notice%c3(%c2%nick%c3)%c2%c1\]%c2 %text"
addform chattext "%c1(%c2%lnick%c1) %c2%text"
addform titlechat "chat(%nick(%user@%host))"
addform channotice "%pre1 %c2notice%c3\[%c2%chan%c3\]%c2 %nick - %text"
  


    


